---
- name: Update apt repo and cache on Ubuntu box
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
- name: Upgrade all packages on servers
  apt:
    upgrade: dist
    force_apt_get: yes
- name: Install common packages
  apt:
    name:
      - wget
    state: present
- name: Import the Elasticsearch PGP Key
  apt_key:
      url: "{{ pgp_key }}"
      validate_certs: no
- name: Add repository definition
  copy:
    dest: "{{ dest_path }}"
    content: "{{ content_path }}"

- name: Install the Elasticsearch package
  apt:
    name: elasticsearch
    state: present
    update_cache: yes
  notify:
    - Start Elasticsearch
    - Enable Elasticsearch

