---
- name: install gpg
  apt:
    name: gnupg,software-properties-common
    state: present
    update_cache: yes
    cache_valid_time: 3600
- name: add gpg key
  apt_key:
    url: "{{ url_path }}"
    validate_certs: no
- name: add repository
  apt_repository:
    repo: "{{ repo_path }}"
    state: present
    validate_certs: no
- name: Upgrade all packages on servers
  apt:
    upgrade: dist
    force_apt_get: yes
- name: install grafana
  apt:
    name: grafana
    state: latest
    update_cache: yes
    cache_valid_time: 3600
- name: start service grafana-server
  systemd:
    name: grafana-server
    state: started
    enabled: yes
- name: wait for service up
  uri:
    url: "{{ httpd }}"
    status_code: 200
  register: __result
  until: __result.status == 200
  retries: 120
  delay: 1
- name: change admin password for grafana gui
  shell: "grafana-cli admin reset-admin-password {{ grafana_admin_password }}"
  register: __command_admin
  changed_when: __command_admin.rc !=0
