---
- name: starting ec2_instance
  ec2:
    instance_ids: "{{ instance_id }}"
    region: us-west-2
    state: running
    wait: yes
  tags:
   - start
   - never
- name: stopping ec2_instance
  ec2:
    instance_ids: "{{ instance_id }}"
    region: us-west-2
    state: stopped
    wait: yes
  tags:
   - stop
   - never
- name: terminating ec2_instance
  ec2:
    instance_ids: "{{ instance_id }}"
    region: us-west-2
    state: absent
    wait: yes
  tags:
   - terminate
   - never
